_wandb_kernel: awsaf49
augment: true
batch_size: 28
bri: 0.15
clip: false
comment: EfficientNetV1B4-1024x512-roi-up=10-lr4-focal-vflip-wb
competition: rsna-bcd
cont:
- 0.8
- 1.2
cutmix_alpha: 2.5
cutmix_prob: 0.0
debug: false
device: TPU-VM
display_plot: true
drop_cnt: 10
drop_prob: 0.6
drop_size: 0.08
epochs: 8
exp_name: roi-v2-fix
fill_mode: constant
fold: 2
folds: 5
hflip: true
hshift: 10.0
hue: 0.05
hzoom: 50.0
img_size:
- 1024
- 512
loss: Focal
mixup_alpha: 0.5
mixup_prob: 0.0
model_name: EfficientNetV1B4
optimizer: Adam
pixel_aug: 0.9
rot: 2.0
sat:
- 0.7
- 1.3
scheduler: exp
seed: 42
selected_folds:
- 0
- 1
- 2
shr: 2.0
target_col:
- cancer
transform: 0.9
tta: 1
upsample: 10
use_cw: false
verbose: 1
vflip: true
wandb: true
wshift: 10.0
wzoom: 50.0
